
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

[<assembly: Android.Runtime.ResourceDesignerAttribute("App2.Resource", IsApplication=true)>]
do ()
namespace App2
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException0bf5733e55d8421695966772da6380ea of obj
    exception ReturnNoneException0bf5733e55d8421695966772da6380ea
    [<AutoOpen>]
    module FuncConvertFinalOverload0bf5733e55d8421695966772da6380ea =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050016
            static member btnAddItem = 2131034134
            
            // aapt resource value: 0x7f050018
            static member buttonInWarehouse = 2131034136
            
            // aapt resource value: 0x7f050019
            static member frameLayout1 = 2131034137
            
            // aapt resource value: 0x7f05000a
            static member gridLayout1 = 2131034122
            
            // aapt resource value: 0x7f050003
            static member lbBarcode = 2131034115
            
            // aapt resource value: 0x7f050001
            static member lbGoodName = 2131034113
            
            // aapt resource value: 0x7f05000d
            static member lbHeight = 2131034125
            
            // aapt resource value: 0x7f05000c
            static member lbLength = 2131034124
            
            // aapt resource value: 0x7f05000b
            static member lbWidth = 2131034123
            
            // aapt resource value: 0x7f050000
            static member linearLayout1 = 2131034112
            
            // aapt resource value: 0x7f050005
            static member linearLayout2 = 2131034117
            
            // aapt resource value: 0x7f050006
            static member radioGroup1 = 2131034118
            
            // aapt resource value: 0x7f050013
            static member rbBag = 2131034131
            
            // aapt resource value: 0x7f050012
            static member rbBox = 2131034130
            
            // aapt resource value: 0x7f050009
            static member rbDefSize = 2131034121
            
            // aapt resource value: 0x7f050014
            static member rbOther = 2131034132
            
            // aapt resource value: 0x7f050008
            static member rbUndefinedSize = 2131034120
            
            // aapt resource value: 0x7f050017
            static member textView1 = 2131034135
            
            // aapt resource value: 0x7f050007
            static member textView6 = 2131034119
            
            // aapt resource value: 0x7f050004
            static member txtBarcode = 2131034116
            
            // aapt resource value: 0x7f050002
            static member txtGoodName = 2131034114
            
            // aapt resource value: 0x7f050010
            static member txtHeight = 2131034128
            
            // aapt resource value: 0x7f05000f
            static member txtLength = 2131034127
            
            // aapt resource value: 0x7f050015
            static member txtOtherType = 2131034133
            
            // aapt resource value: 0x7f05000e
            static member txtWidth = 2131034126
            
            // aapt resource value: 0x7f050011
            static member typeChoicer = 2131034129
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member AddItem = 2130903040
            
            // aapt resource value: 0x7f030001
            static member AddItemOnWarehouse = 2130903041
            
            // aapt resource value: 0x7f030002
            static member Main = 2130903042
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040001
            static member ApplicationName = 2130968577
            
            // aapt resource value: 0x7f040000
            static member Hello = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

